### ISSUE TITLE
Exception using ACTION_APPLICATION_DETAILS_SETTINGS

### ISSUE THREAD

**Issue by d-wolf** [gyagapen/access_settings_mu#1]
Calling

````Dart
 var resultSettingsOpening =
                    await AccessSettingsMenu.openSettings(
                        settingsType: 'ACTION_APPLICATION_DETAILS_SETTINGS');
````

leads to the following exception:

```` Cmd
E/MethodChannel#access_settings_menu(26272): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#access_settings_menu(26272): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#access_settings_menu(26272): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#access_settings_menu(26272): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#access_settings_menu(26272): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#access_settings_menu(26272): 	at android.app.ActivityThread.main(ActivityThread.java:7529)
E/MethodChannel#access_settings_menu(26272): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#access_settings_menu(26272): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/MethodChannel#access_settings_menu(26272): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
````
.

````Cmd
Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale de-DE)
    • Flutter version 1.0.0 at C:\flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\daniel\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.30.2)
    • VS Code at C:\Users\daniel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] VS Code, 64-bit edition
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • FIG LX1 • XEDDU18122003040 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
````

**Comment by gyagapen** [comment]
As per the Android documentation, you should pass the package name when calling this intent.

However, this package does not support extra arguments for now.

I will update it and let you know.

**Comment by saravananmnm** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'access_settings_menu'.
> Failed to notify project evaluation listener.
   > org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(Ljava/lang/String;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s


The plugin access_settings_menu could not be built due to the issue above.

**Comment by saravananmnm** [comment]
[√] Flutter (Channel master, v1.10.15-pre.137, on Microsoft Windows [Version 10.0.18362.418], locale en-IN)
    • Flutter version 1.10.15-pre.137 at C:\Saravanan\Flutter_Sdk\flutter
    • Framework revision b9817b4f59 (3 days ago), 2019-10-15 17:36:34 -0700
    • Engine revision 540fc977bb
    • Dart version 2.6.0 (build 2.6.0-dev.7.0 70a7ef3f58)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Genymotion • 192.168.34.101:5555 • android-x86 • Android 9 (API 28)
